/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated.search'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated.report'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated.items.$itemId'
import { Route as AuthenticatedItemsItemIdClaimRouteImport } from './routes/_authenticated.items.$itemId.claim'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsItemIdClaimRoute =
  AuthenticatedItemsItemIdClaimRouteImport.update({
    id: '/claim',
    path: '/claim',
    getParentRoute: () => AuthenticatedItemsItemIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/report': typeof AuthenticatedReportRoute
  '/search': typeof AuthenticatedSearchRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRouteWithChildren
  '/items/$itemId/claim': typeof AuthenticatedItemsItemIdClaimRoute
}
export interface FileRoutesByTo {
  '/report': typeof AuthenticatedReportRoute
  '/search': typeof AuthenticatedSearchRoute
  '/': typeof AuthenticatedIndexRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRouteWithChildren
  '/items/$itemId/claim': typeof AuthenticatedItemsItemIdClaimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/items/$itemId': typeof AuthenticatedItemsItemIdRouteWithChildren
  '/_authenticated/items/$itemId/claim': typeof AuthenticatedItemsItemIdClaimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report'
    | '/search'
    | '/items/$itemId'
    | '/items/$itemId/claim'
  fileRoutesByTo: FileRoutesByTo
  to: '/report' | '/search' | '/' | '/items/$itemId' | '/items/$itemId/claim'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/report'
    | '/_authenticated/search'
    | '/_authenticated/'
    | '/_authenticated/items/$itemId'
    | '/_authenticated/items/$itemId/claim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId': {
      id: '/_authenticated/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId/claim': {
      id: '/_authenticated/items/$itemId/claim'
      path: '/claim'
      fullPath: '/items/$itemId/claim'
      preLoaderRoute: typeof AuthenticatedItemsItemIdClaimRouteImport
      parentRoute: typeof AuthenticatedItemsItemIdRoute
    }
  }
}

interface AuthenticatedItemsItemIdRouteChildren {
  AuthenticatedItemsItemIdClaimRoute: typeof AuthenticatedItemsItemIdClaimRoute
}

const AuthenticatedItemsItemIdRouteChildren: AuthenticatedItemsItemIdRouteChildren =
  {
    AuthenticatedItemsItemIdClaimRoute: AuthenticatedItemsItemIdClaimRoute,
  }

const AuthenticatedItemsItemIdRouteWithChildren =
  AuthenticatedItemsItemIdRoute._addFileChildren(
    AuthenticatedItemsItemIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
